### PR TITLE
Release 0.10.0

### PR DESCRIPTION
**Pull request by nokara26**
I want to release 0.9.4.
This release includes following PR. #81 #82

### CODE REVIEW

**Review by totakke — CHANGES_REQUESTED** [review]
Thank you so much, but #82 includes a little breaking change.
Even though it is a bug fix, it causes an error to a conversion that was wrong but succeeded before.
So I recommend bumping up the version to `0.10.0` instead of `0.9.4`.

**Comment by federkasten** [comment]
@totakke Thank you for reviewing :pray: 
I am in a bit of a hurry for the release, so I have fixed it as 0.10.0 on behalf of @nokara26.

**Review by totakke — APPROVED** [review]
LGTM

**Comment by totakke** [comment]
Thank you for your quick fix.

Just deployed: https://clojars.org/varity/versions/0.10.0

**Comment by federkasten** [comment]
Thanks! :+1:

**Pull request merged**
