### PR TITLE
Release 0.9.2

### PR DESCRIPTION
**Pull request by nokara26**
I want to release 0.9.2.

Let me know if there was something missing for a release PR🙇

### CODE REVIEW

**Review by totakke — CHANGES_REQUESTED** [review]
Thank you for preparing the release. Please run `lein codox` to update documents in `docs/` directory.

**Comment by nokara26** [comment]
> Thank you for preparing the release. Please run `lein codox` to update documents in `docs/` directory.

Thank you for letting me know how to release, I did it!

**Review by totakke — APPROVED** [review]
LGTM

**Comment by totakke** [comment]
Thank you for updating the documents.

I have just deployed varity `0.9.2` to Clojars. https://clojars.org/varity

**Pull request merged**
